assets/sass/custom.sass, config.toml, content/test-content/docs-section-1/_index.md, layouts/index.html, layouts/partials/footer.html, layouts/partials/github-edit.html, layouts/partials/home/cncf-status.html, layouts/partials/navbar.html, layouts/partials/section-nav.html, layouts/partials/social-buttons.html
- Update twitter button, still need to update for project, but it links now (https://github.com/containernetworking/cni.dev/issues/11)
- CNCF Branding Elements and Copyright (fixes items 5, 6, 7 of issue https://github.com/containernetworking/cni.dev/issues/6)
- Correct "Edit on GitHub" button (fixes https://github.com/containernetworking/cni.dev/issues/5)
- Correct linkTitle use (fixes https://github.com/containernetworking/cni.dev/issues/4)
=> Corrections from upstream

LICENSE
Fixes https://github.com/containernetworking/cni.dev/issues/1
=> Adding Apache License 2.0

config.toml
Removing twitter button as [per feedback](https://docs.google.com/document/d/1SIcIzndh6DYs3cZRA8f8_CSbgzCYQxO-0lNrI7fEjhY/edit#heading=h.srmpijc6p10e).
Fixes #11.
=> Removing Twitter Button

content/plugins/plugins/ipam/dhcp/_index.md, content/plugins/plugins/meta/vrf/_index.md
Copy updated from source repo containernetworking/plugins
fixes https://github.com/containernetworking/cni.dev/issues/45
=> Updating copy

layouts/partials/deprecation-warning.html, layouts/partials/social-buttons.html
Updating deprecation warning & social buttons
fixes: https://github.com/containernetworking/cni.dev/issues/47
fixes https://github.com/containernetworking/cni.dev/issues/48
=> Updating deprecation warning & social buttons

README.md, content/docs/_index.md, content/plugins/_index.md
Updating README.md, plugins main page, and cni docs main page.
fixes: https://github.com/containernetworking/cni.dev/issues/18
fixes: https://github.com/containernetworking/cni.dev/issues/27
fixes: https://github.com/containernetworking/cni.dev/issues/28
fixes: https://github.com/containernetworking/cni.dev/issues/29
=> Copy edits

config.toml
Adding v0.6.0 and v0.7.6
Fixes #53 
Fixes #54
=> Updating Versions Menu

netlify.toml
Correcting HUGO_BASEURL
fixes #56
=> Updating netlify.toml

content/plugins/meta/firewall.md
Adding json formatting to last example. 
Standardizing indentation on samples throughout page.
=> formatting update on plugins/meta/firewall.md

content/plugins/ipam/dhcp.md
Documentation for change in containernetworking/plugins#577
=> Add -broadcast flag to DHCP plugin documentation

content/plugins/current/main/bridge.md
Ref: https://github.com/containernetworking/plugins/pull/636
=> bridge plugin: Document the mac field argument

content/plugins/current/meta/tuning.md
Ref: https://github.com/containernetworking/plugins/pull/669
Signed-off-by: Piotr Skamruk <piotr.skamruk@gmail.com>
=> Update docs after plugins#669 - IFNAME on tuning plugin

content/plugins/current/meta/firewall.md
The ingressPolicy parameter was implemented in https://github.com/containernetworking/plugins/pull/584 .
Merged into the master on Feb 10, 2022: https://github.com/containernetworking/plugins/commit/42268a4a93f6425413d4c840aa8717496ced12a0 (v1.1.0)
=> firewall: document ingressPolicy=(open|same-bridge)

content/plugins/current/main/bridge.md
Updating the bridge documentation to include 'enabledad'
Related Issue: 
https://github.com/containernetworking/plugins/issues/680
Related PR:
https://github.com/containernetworking/plugins/pull/695
=> Update bridge documentation to include 'enabledad'

config.toml, content/plugins/v1.1/_index.md, content/plugins/v1.1/ipam/_index.md, content/plugins/v1.1/ipam/dhcp.md, content/plugins/v1.1/ipam/host-local.md, content/plugins/v1.1/ipam/static.md, content/plugins/v1.1/main/_index.md, content/plugins/v1.1/main/bridge.md, content/plugins/v1.1/main/host-device.md, content/plugins/v1.1/main/ipvlan.md, content/plugins/v1.1/main/macvlan.md, content/plugins/v1.1/main/ptp.md, content/plugins/v1.1/main/vlan.md, content/plugins/v1.1/main/win-bridge.md, content/plugins/v1.1/main/win-overlay.md, content/plugins/v1.1/meta/_index.md, content/plugins/v1.1/meta/bandwidth.md, content/plugins/v1.1/meta/firewall.md, content/plugins/v1.1/meta/portmap.md, content/plugins/v1.1/meta/sbr.md, content/plugins/v1.1/meta/tuning.md, content/plugins/v1.1/meta/vrf.md
Signed-off-by: Michael Zappa <Michael.Zappa@stateless.net>
=> Update docs to include v1.1

content/plugins/current/meta/portmap.md
PR refer: https://github.com/containernetworking/plugins/pull/772
=> Add masqAll feature description

content/plugins/current/main/tap.md
Signed-off-by: mmirecki <mmirecki@redhat.com>
=> Tap plugin documentation

content/plugins/current/main/ipvlan.md, content/plugins/current/main/macvlan.md, content/plugins/current/main/vlan.md
Documenting: https://github.com/containernetworking/plugins/pull/781
=> Add description of vlan plugin linkInContainer parameter

content/docs/owners.md
Signed-off-by: Michael Zappa <Michael.Zappa@stateless.net>
=> Update CNI Maintainers

content/plugins/current/main/tap.md
Fixes: https://github.com/containernetworking/cni.dev/issues/114
=> Fix plugin type in tap plugin

content/plugins/current/main/bridge.md
Linked to https://github.com/containernetworking/plugins/pull/875
=> Add preserveDefaultVlan parameter

content/docs/spec-upgrades.md, content/docs/spec.md
Just copying the document from the cni repo: https://github.com/containernetworking/cni/blob/v1.2.3/SPEC.md
I also added the changes of cni v1.1 to the specs-upgrade document.
=> Update specs to latest version (v1.1)

content/plugins/current/meta/firewall.md
This adds documentation for the new 'isolated' ingress policy in bridge firewall plugin
Merged in https://github.com/containernetworking/plugins/pull/1140
Tested locally using `make docker-serve`
=> Add 'isolated' ingress policy documentation for firewall plugin
