.editorconfig

correcting .editorconfig for markdown files, will not strip whitespace from line ends in markdown files.

Fix .editorconfig file

---

config.toml

By default Hugo puts some cache information outside of its cacheDir. Set
Hugo to write all cached files inside the configured cache directory.

v0.6.0_always_cache_into_cachedir

---

config.toml

By default Hugo puts some cache information outside of its cacheDir. Set
Hugo to write all cached files inside the configured cache directory.

v0.7.6_always_cache_into_cachedir

---

config.toml

By default Hugo puts some cache information outside of its cacheDir. Set
Hugo to write all cached files inside the configured cache directory.

v0.8.6_always_cache_into_cachedir

---

config.toml

By default Hugo puts some cache information outside of its cacheDir. Set
Hugo to write all cached files inside the configured cache directory.

v0.8.7_always_cache_into_cachedir

---

content/plugins/meta/firewall.md

Correct me if I am wrong, I am pretty sure these flags are swapped in the README which caused a small confusion as I was reading it. We can refer to https://github.com/containernetworking/plugins/blob/master/plugins/meta/firewall/iptables.go#L31&#L32 to see what they really are set to.
I was originally going to open the fix in the plugins repo, but then I saw this PR https://github.com/containernetworking/plugins/pull/549 that is migrating everything to this repo.

Fixing a typo in Firewall README

---

assets/sass/custom.sass

As per [feedback session](https://docs.google.com/document/d/1SIcIzndh6DYs3cZRA8f8_CSbgzCYQxO-0lNrI7fEjhY/edit#heading=h.srmpijc6p10e), reducing logo size in jumbotron.
Does this size work better for you @dcbw?
Fixes #39

reducing logo size in jumbotron

---

config.toml

Updating current site (www.cni.dev) versions menu with v0.9.0
Deploy preview: https://deploy-preview-71--cni.netlify.app/

Updating current site (www.cni.dev) versions menu with v0.9.0

---

config.toml

Updating v0.6.0 site (v0-6-0.cni.dev) versions menu with v0.9.0
Deploy preview: https://deploy-preview-72--v0-6-0-cni.netlify.app/

Updating v0.6.0 site (v0-6-0.cni.dev) versions menu with v0.9.0

---

config.toml

Updating v0.7.6 site (v0-7-6.cni.dev) versions menu with v0.9.0
Deploy preview: https://deploy-preview-73--v0-7-6-cni.netlify.app/

Updating v0.7.6 site (v0-7-6.cni.dev) versions menu with v0.9.0

---

config.toml

Updating v0.8.6 site (v0-8-6.cni.dev) versions menu with v0.9.0
Deploy preview: https://deploy-preview-74--v0-8-6-cni.netlify.app/

Updating v0.8.6 site (v0-8-6.cni.dev) versions menu with v0.9.0

---

config.toml

Updating v0.8.7 site (v0-8-7.cni.dev) versions menu with v0.9.0
Deploy preview: https://deploy-preview-75--v0-8-7-cni.netlify.app/

Updating v0.8.7 site (v0-8-7.cni.dev) versions menu with v0.9.0

---

content/plugins/main/host-device.md

Update host-device readme for supporting dpdk device. 
Here is the dependent [PR](https://github.com/containernetworking/plugins/pull/490).
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

update host-device readme for dpdk support

---

content/plugins/ipam/dhcp.md

What
----
Documents the `timeout` flag from https://github.com/containernetworking/plugins/pull/565

Document timeout flag for DHCP daemon

---

content/plugins/current/meta/tuning.md

This is the corresponding documentation updates for PR: containernetworking/plugins#624
A preview of the changes can be seen at:
https://bjosv-deploy-preview-allmulti.netlify.app/plugins/current/meta/tuning/

tuning: Add documentation for the allmulti flag

---

content/plugins/current/ipam/dhcp.md

Add description and example about DHCP options. See containernetworking/plugins#670 and containernetworking/plugins#660 for details.
Signed-off-by: SilverBut <SilverBut@users.noreply.github.com>

Plugins(dhcp): add examples about DHCP options

---

content/plugins/current/_index.md
content/plugins/current/main/_index.md
content/plugins/current/main/vlan.md

I noticed for a while that the vlan plugin documentation was missing. I wanted to get the ball rolling on it. I wasn't sure if I should put this in current and 1.0.0 or the other directory? If the maintainers have a preference I can update the PR.

Provide vlan plugin documentation

---

content/plugins/current/main/bridge.md

Following https://github.com/containernetworking/plugins/pull/997, update docs regarding the new disableContainerInterface flag.

bridge: Disable container interface

---

content/plugins/current/main/bridge.md
content/plugins/current/main/ptp.md
content/plugins/current/meta/portmap.md

(to sync with https://github.com/containernetworking/plugins/pull/935)
Also belatedly remove the recommendation of using `"externalSetMarkChain": "KUBE-MARK-MASQ"`.
cc @squeed @aojea

Document nftables backends for portmap and ipmasq

---

content/plugins/current/main/bridge.md

Following https://github.com/containernetworking/plugins/pull/1141, update docs regarding the new portIsolation flag.

bridge: Port isolation support

---

content/plugins/current/main/bridge.md

Tiny fix for the recently added bridge example's json formatting.

bridge: Fix example json formatting

---

content/plugins/current/meta/portmap.md

Was reading https://www.cni.dev/plugins/current/meta/portmap/#rule-structure-nftables and found the tailing sections mis-formatted.

Fix code format in portmap.md for nftables
